default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: lala020485
  pool: 5
  timeout: 5000
  host: localhost
development:
  <<: *default
  database: postgres
test:
  <<: *default
  database: <%= ENV['POSTGRES_TEST_DB'] %>
production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>